language: go
go:
  - 1.14.x
  - 1.15.x
  - master

matrix:
  allow_failures:
  - go: master

# script:
# - go run main.go

before_deploy:
  - export XCOMPILE='go build -o hcl2json_${TRAVIS_TAG}_${GOOS}_${GOARCH}${EXT} -ldflags="-X main.Version=${TRAVIS_TAG#v}" github.com/tmccombs/hcl2json'
  - GOOS=linux   GOARCH=386            eval "$XCOMPILE"
  - GOOS=linux   GOARCH=amd64          eval "$XCOMPILE"
  - GOOS=linux   GOARCH=arm            eval "$XCOMPILE"
  - GOOS=darwin  GOARCH=386            eval "$XCOMPILE"
  - GOOS=darwin  GOARCH=amd64          eval "$XCOMPILE"
  - GOOS=windows GOARCH=386   EXT=.exe eval "$XCOMPILE"
  - GOOS=windows GOARCH=amd64 EXT=.exe eval "$XCOMPILE"
deploy:
  provider: releases
  api_key:
    secure: d9Its7sfeJIDQziD/MY/A2N3gV3rzs/mecd3/o2HgAUsvA10GM1eKSioe1MqFOoI158E2FERMwwgYztzvQT44bN8R3WtCR8zs07ZHCJrcQIx49R4g43KPxfsuEWFtx7kvEDbzF8at+F9GjTu7gi2SXrU6zoPIP6gsh7In9iuswBb1cI9I/YjwFNNh5hDmm9+MOAWFkNqi17F3qx2JGkUloZZOz/Sldx3Ga9cruIdAltr8Fzc4h4M2LVrNlz1gAA+lVHFNLYHoad014PgmwERx9D2xEfelMhYMcWUAbRDfB6TkH/AIuMgAH9k8hMe7QGXFIj4YP+gjR/ZYwnJ3QfHOad2dMs9vtV2j8SnxdSSDxZGUrXCrsDmBJpiLuFvQYH58CkUwAuqQ4kALLC46bq6W2RJ0InMwvSFcVxsLLvSUIMPWCYTdEUl3Nj8mYb3+WialYKTrFLcSXLIukJTGP96Au4C0tuNxnx8n0ovnx9/6eDJkPiC4113/j6gMyChAa/+zPric4poirH/COnhAbyURxAdfa5GuFbSc67k9riROPQ0NHJaKfYLDY0Zedu/mxaq1l/1iXNorDrfBTqw3BlITMzHuUYJ35NFVGesvnuKnQe9FJ1SZQjYm9fp5LnLzXDbxkWQfz8doThgDEN8wmRLoXsSqISkoPO7RbI+9OMKdOA=
  file_glob: true
  file: hcl2json_*
  skip_cleanup: true
  on:
    tags: true
    go: 1.14.x
    repo: tmccombs/hcl2json
