language: go
go:
  - 1.12.x
  - master

matrix:
  allow_failures:
  - go: master

# script:
# - go run main.go

before_deploy:
  - export XCOMPILE='go build -o hcl2json_${TRAVIS_TAG}_${GOOS}_${GOARCH}${EXT} -ldflags="-X main.Version=${TRAVIS_TAG}" github.com/tmccombs/hcl2json'
  - GOOS=linux   GOARCH=386            eval "$XCOMPILE"
  - GOOS=linux   GOARCH=amd64          eval "$XCOMPILE"
  - GOOS=linux   GOARCH=arm            eval "$XCOMPILE"
  - GOOS=darwin  GOARCH=386            eval "$XCOMPILE"
  - GOOS=darwin  GOARCH=amd64          eval "$XCOMPILE"
  - GOOS=windows GOARCH=386   EXT=.exe eval "$XCOMPILE"
  - GOOS=windows GOARCH=amd64 EXT=.exe eval "$XCOMPILE"
deploy:
  provider: releases
  api_key:
    secure: OjHn9bA2SQVXwN5rRkSqVPGJSIAiFHcYK/9t3izPOFeiTwNhPJQkF4zY8GfjEyNI/wpjUqzoL5khhcjR3nCClgbk6fV+6ftiDR7ecgQX2ocPjwfWyECOohKR2tg2tL7vjPDSDwpaGvaLbSD6+HpX92cI9bLjF1FZ3ZiQ07NpPKvvtk9jkSLPKd5DWpskKPgd3zTo4qwrGtyuovGWbepssZywl7TYYxgkGAOemdmmcmUXLbANY3SZKYIB42ew36Ik3/OMvuBAPVRNbUdUrzJh6YE8DwzGoHBnEDztK38wJq3J166rinTcqyaVDrkqIdSAITrX6yw6wCrRfMelXc2/uR3sVBCuK0I2OKlqR0HnuRfBD5NE4IOM2fVqwGzQXhMJaGO1XEPrOQcdxo6O6+jzSPgJseOV8WNu72kOJIH/nVDdXtbtIKhDOrvQvb95kZT9IDS2wDdF6IFn6tgKhhDHS2QqMl3oOz60Lr3u71jw8bz+z7mx91WF2zkN+yffdrEKyRMrdQRjYt2yRDE3DyHNG1IZIDmA/EcQWiy9rPge1i1jR34TK5GcKElIY2TDR9mOUKOan7KjnyfRxj2JaAo49xsPaG3lUr3qzys2iLM+X+xUU+kbqHCGhQNn9EU/1x4abtHrl4Uhn45MNaKwXLGolD80GCGTAGSk6q8qeitI9yw=
  file_glob: true
  file: hcl2json_*
  skip_cleanup: true
  on:
    tags: true
    go: 1.12.x
    repo: tmccombs/hcl2json
