language: go
go:
  - 1.12.x
  - master

matrix:
  allow_failures:
    - go: master

# script:
# - go run main.go

before_deploy:
  - export XCOMPILE='go build -o hcl2json_${TRAVIS_TAG}_${GOOS}_${GOARCH}${EXT} -ldflags="-X main.Version=${TRAVIS_TAG}" github.com/tmccombs/hcl2json'
  - GOOS=linux   GOARCH=386            eval "$XCOMPILE"
  - GOOS=linux   GOARCH=amd64          eval "$XCOMPILE"
  - GOOS=linux   GOARCH=arm            eval "$XCOMPILE"
  - GOOS=darwin  GOARCH=386            eval "$XCOMPILE"
  - GOOS=darwin  GOARCH=amd64          eval "$XCOMPILE"
  - GOOS=windows GOARCH=386   EXT=.exe eval "$XCOMPILE"
  - GOOS=windows GOARCH=amd64 EXT=.exe eval "$XCOMPILE"
deploy:
  provider: releases
  api_key:
    secure: "HmQ03kaPsxNPK8uZ0hMRZgeZKO5nkrk7jdz74jRaAxOZKBxkTwgmGo2uw2z/XIxefXCTkWQpqhjodm0iTNLdsRWprhRd67ubmV+3yHtNe2d8LV/jzlOmK40V+DgbPvIlOXfujihGCasX1UNUG6qqhJi0MPP6eEaShYnPVNGzGBj3qeyrN1nVzRL46BiWSLzpaWR6TvhzFJC/NVI7+hksZh4v4TizqIHezQzB70vK5p1YSgKTagElJ78uEIHS4+qzq6YuCyL1tdq+MXM1eskWCb2za26odsaAnDie26KH9J9k6OjMa4kfoSSCyWyWWwK5HH4Stg1MyQUE4l0InImxiJRIf9Gav7BNBhaJ2v8fGu7iyLjxlFgp9c9sbQAMEBYeoXqfHDvWCvVGTd41ox52em99pt0w7qMNFZVEHRl62bZ3UuH1uIw+Cwo2gSWD9Dj3Lmk0HGRUNA08esgk6bNlIScfV40ph5kPtGQUQSyY9ka8q3lEt85HyUMD5Jl9ADawBt9BjQEqieT6xOcf5WaBw6SPEnABVDl0Sx+rdaDS3jLU9tHNKDJi8bSDdfMGbJ2ksVwftgl3AFhoutbewZIKmfyLI30lPmZ6toq6K81XU1IzSiwdo5W0TfTHgILDeNrYGczAVHfuwhGJBI8N7eLxRnub8w9ccnzG9sza8kw7Wo4="
  file_glob: true
  file: hcl2json_*
  skip_cleanup: true
  on:
    tags: true
    go: 1.12.x
    repo: tmccombs/hcl2json
